### ISSUE TITLE
POS & Inventory Management

### ISSUE THREAD

**Issue by bldambtn** [bldambtn/MyPOSisBetterThanYourPOS#1]
## User Story 1: Business Owner Login
As a business owner, I want to log in to the system using my credentials so that I can securely access my dashboard.

## Acceptance Criteria:

- The login page is accessible from the homepage.
- Users can enter their username and password to log in.
- The system uses JWT to authenticate users.
- After successful login, the user is redirected to the dashboard.
- If login fails, an error message is displayed.

**Comment by nhl1090** [comment]
Ensure username login.

**Comment by nhl1090** [comment]
Success. Issue closed.
